# Generated by Django 3.2.7 on 2021-10-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anchorapp', '0002_auto_20210929_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default='cat.jpg', upload_to='category')),
                ('min_quant', models.IntegerField(default=1)),
                ('max_quant', models.IntegerField()),
                ('latest', models.BooleanField()),
                ('best_seller', models.BooleanField()),
                ('available', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anchorapp.category')),
            ],
        ),
    ]
