# Generated by Django 3.2.7 on 2021-10-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anchorapp', '0003_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
